@startuml
Car *-right- Engine
Car o-- RacingCircuit
class Car{
    -wheels: array
    -engine: Engine
    + __construct(Engine)
    +movingForward(int):void
    +brake():void
}

class Engine{
    start():void

}

class RacingCircuit{
    -cars: ?array
    isLive():Boolean
}

@enduml
